(function (root) {
  'use strict';
  const node = typeof module !== 'undefined' && module.exports;
  const C = node ? require('../state.js') : root.TecState;
  const U = node ? require('../ui.js') : root.TecUI;
  const A = node ? require('./pulse-actions.js') : root.TecPulseActionsView;
  const { e, icon } = U;
  function art(kind, hero = false) {
    if (hero) return `<svg class="hero-art" viewBox="0 0 480 320" role="img" aria-label="Ilustración conceptual de ideas y personas conectadas"><defs><linearGradient id="hero-g" x1="0" x2="1" y1="0" y2="1"><stop stop-color="#356bd2"/><stop offset="1" stop-color="#16449f"/></linearGradient></defs><circle cx="260" cy="172" r="122" fill="none" stroke="#7199e9" stroke-opacity=".35"/><circle cx="260" cy="172" r="91" fill="none" stroke="#7199e9" stroke-opacity=".35"/><path d="M96 184L242 68 389 164 270 263Z" fill="none" stroke="#9ebdf7" stroke-width="2" stroke-dasharray="5 8"/><g transform="translate(173 87) rotate(-8 84 63)"><rect width="170" height="128" rx="14" fill="#fff"/><rect x="17" y="18" width="48" height="7" rx="3" fill="#cadcfb"/><path d="M55 69a28 28 0 1 1 55 0c0 17-16 19-17 31H73C72 88 55 86 55 69Z" fill="#f5ca6b"/><path d="M75 107h16" stroke="#0039a6" stroke-width="4" stroke-linecap="round"/><path d="M83 78V56m-9 8 9-8 9 8" fill="none" stroke="#0039a6" stroke-width="3" stroke-linecap="round"/><circle cx="149" cy="108" r="5" fill="#b7d9d3"/></g><g transform="translate(48 154) rotate(7 45 37)"><rect width="104" height="86" rx="12" fill="#dbe9ff"/><circle cx="52" cy="33" r="14" fill="#6693de"/><path d="M27 66c0-18 50-18 50 0" fill="#6693de"/><path d="M81 15h9m-4-4v8" stroke="#0039a6" stroke-width="2" stroke-linecap="round"/></g><g transform="translate(347 123) rotate(9 45 36)"><rect width="91" height="78" rx="12" fill="#dbe9ff"/><path d="m25 35 13-12m-13 12 13 12m28-12L53 23m13 12L53 47m-6-28-7 32" stroke="#0039a6" stroke-width="3" stroke-linecap="round" fill="none"/><rect x="26" y="60" width="39" height="4" rx="2" fill="#aac6f4"/></g><circle cx="258" cy="268" r="27" fill="#a7d1c8"/><path d="m248 268 7 7 14-16" fill="none" stroke="#0039a6" stroke-width="3" stroke-linecap="round"/><circle cx="242" cy="56" r="8" fill="#f5ca6b"/><circle cx="79" cy="106" r="5" fill="#a7d1c8"/><path d="M364 65h15m-7-7v15M155 277h12m-6-6v12" stroke="#a8c5fa" stroke-width="2"/><circle cx="411" cy="253" r="6" fill="#86acee"/></svg>`;
    const pictures = {
      ideas: `<circle cx="253" cy="69" r="90" fill="none" stroke="#9bbcf6" stroke-width="25"/><path d="m156 106 57-77 73 93" fill="none" stroke="#e3edff" stroke-width="2"/><rect x="180" y="40" width="73" height="64" rx="8" fill="#fff" transform="rotate(-9 216 70)"/><path d="M204 70a13 13 0 1 1 26 0c0 9-7 10-7 17h-13c0-7-6-8-6-17" fill="#edc66c"/><circle cx="152" cy="115" r="11" fill="#aad4c8"/>`,
      prototype: `<path d="M157 120 200 31 283 78 242 147Z" fill="#aebce9"/><rect x="172" y="43" width="86" height="67" rx="8" fill="#fff" transform="rotate(-7 215 76)"/><rect x="187" y="58" width="27" height="32" rx="4" fill="#dfc7e7"/><path d="M225 59h20m-20 10h15m-20 21h25" stroke="#7282bc" stroke-width="4" stroke-linecap="round"/><circle cx="280" cy="34" r="12" fill="#f1cf88"/>`,
      garden: `<path d="M211 141V63" stroke="#588b72" stroke-width="4"/><path d="M211 104c-42 0-57-33-57-33 37-8 57 13 57 33m0-20c45 1 52-44 52-44-39 0-52 22-52 44" fill="#92bea6"/><path d="M184 124h57l-9 25h-39Z" fill="#dae8db"/><circle cx="271" cy="30" r="15" fill="#e7c66e"/><path d="M152 138h114" stroke="#aac8b1" stroke-width="2"/>`,
      stories: `<rect x="175" y="29" width="69" height="92" rx="7" fill="#b8cbed" transform="rotate(-11 209 75)"/><rect x="204" y="37" width="71" height="94" rx="7" fill="#fff" transform="rotate(6 239 84)"/><path d="M217 59h44m-44 13h34m-34 13h44m-44 13h28" stroke="#8aa5d6" stroke-width="4" stroke-linecap="round"/><circle cx="162" cy="112" r="11" fill="#cbdde8"/>`,
      access: `<rect x="161" y="40" width="114" height="74" rx="8" fill="#fff"/><path d="M161 59h114" stroke="#e5d8ef" stroke-width="2"/><circle cx="175" cy="50" r="3" fill="#b5a0c5"/><circle cx="185" cy="50" r="3" fill="#b5a0c5"/><circle cx="195" cy="50" r="3" fill="#b5a0c5"/><circle cx="217" cy="74" r="7" fill="#a18cbb"/><path d="M200 88h34m-17-7v22m0-8-10 10m10-10 10 10" stroke="#a18cbb" stroke-width="3" stroke-linecap="round"/><path d="M286 104h12m-6-6v12" stroke="#a18cbb" stroke-width="2"/>`,
      circular: `<circle cx="225" cy="82" r="39" fill="none" stroke="#b2ccb5" stroke-width="16"/><path d="m225 27 17 18-24 3m5 89-16-18 24-3" fill="#679376"/><rect x="210" y="67" width="31" height="31" rx="4" fill="#fff" transform="rotate(-10 225 82)"/><circle cx="282" cy="42" r="12" fill="#edc982"/>`
    };
    return `<svg class="cover-svg" viewBox="0 0 320 160" aria-hidden="true">${pictures[kind] || pictures.ideas}<path d="M24 121h52m-52 9h34" stroke="currentColor" stroke-width="3" opacity=".25" stroke-linecap="round"/></svg>`;
  }

  function hero() {
    return `<section class="pulse-hero" aria-label="Evento destacado"><div class="hero-copy"><span class="hero-eyebrow">${icon('auto_awesome')}Un encuentro, muchas posibilidades</span><h2>Las ideas crecen<br>cuando se encuentran.</h2><p>Trae tu curiosidad al Laboratorio de ideas.<br class="desktop-break"> El siguiente paso puede empezar con alguien más.</p><div class="hero-meta">${icon('calendar_month')}Viernes 9 oct · 16:00 <span>·</span> CEM</div><a class="button hero-button" href="#/pulse/laboratorio-ideas">Explorar evento ${icon('arrow_forward')}</a></div>${art('ideas', true)}<span class="art-caption">Ilustración conceptual</span></section>`;
  }

  function filters({ state }) {
    return `<div class="filter-pills" role="group" aria-label="Filtrar publicaciones por categoría">${[['all', 'Todo'], ['events', 'Eventos y talleres'], ['news', 'Artículos'], ['opportunities', 'Oportunidades'], ['saved', 'Guardados']].map(([value, label]) => `<button type="button" id="pulse-filter-${value}" data-filter="pulse" data-value="${value}" aria-pressed="${state.filters.pulse === value}" class="filter-pill${state.filters.pulse === value ? ' selected' : ''}">${label}</button>`).join('')}</div>`;
  }
  function modes({ state }) {
    const effective = C.effectivePulseMode(state);
    const available = state.pulsePreferences.enabled && C.hasPulseTopics(state);
    return `<div class="pulse-personalization"><div class="pulse-modes" role="group" aria-label="Contenido de Campus Pulse">${[['forYou', 'Para ti'], ['all', 'Todo el campus']].map(([value, label]) => `<button type="button" id="pulse-mode-${value}" data-pulse-mode="${value}" aria-pressed="${effective === value}" class="pulse-mode${effective === value ? ' selected' : ''}"${value === 'forYou' && !available ? ' disabled aria-describedby="pulse-mode-note"' : ''}>${label}</button>`).join('')}</div><a class="text-link pulse-customize" href="#/profile/preferences">${icon('tune')}Personalizar dashboard</a><p id="pulse-mode-note" class="pulse-mode-note">${effective === 'forYou' ? 'Primero verás publicaciones que coinciden con tus temas guardados. También puedes explorar todo el campus.' : available ? 'Explora todas las publicaciones en su orden general.' : 'Elige temas y activa la personalización en Preferencias para ver contenido para ti.'}</p></div>`;
  }
  function reason(item, { state }) {
    const matches = C.pulseMatchTopics(state, item);
    if (!matches.length) return '';
    // The label names the preference group that produced the match.
    const label = item.category === 'opportunities' ? `Por tu área de búsqueda: ${e(matches[0].label)}` : `Por tu interés en ${e(matches[0].label)} · ${item.category === 'events' ? 'Eventos' : 'Lecturas'}`;
    return `<span class="pulse-reason">${icon('interests')}${label}</span>`;
  }
  function topicChips(item) {
    const topics = (item.topics || []).map(id => C.topicTaxonomy.find(topic => topic.id === id)).filter(Boolean);
    return `<div class="pulse-topic-tags" role="list" aria-label="Temas de esta publicación">${topics.map(topic => `<span class="pulse-topic-tag" role="listitem" data-topic="${e(topic.id)}">${e(topic.label)}</span>`).join('')}</div>`;
  }
  function saveButton(item, { state }, context, detail = false) {
    const saved = state.saved.includes(item.id);
    return `<button type="button" id="save-${e(context)}-${e(item.id)}" class="${detail ? 'button ' + (saved ? 'secondary' : 'primary') : 'save-button' + (saved ? ' saved' : '')}" data-save="${e(item.id)}" data-save-context="${e(context)}" aria-pressed="${saved}" aria-label="${saved ? 'Quitar de guardados' : 'Guardar'}: ${e(item.title)}">${icon(saved ? 'bookmark_added' : 'bookmark')}<span>${detail ? saved ? 'Guardado · quitar' : 'Guardar publicación' : saved ? 'Guardado' : 'Guardar'}</span></button>`;
  }
  function sourceCTA(item, ctx, classes = 'text-link') {
    if (item.kind === 'article') return U.outboundLink(item.articleUrl, 'Leer artículo completo', ctx.items, classes);
    if (item.kind === 'internship') return U.outboundLink(item.ctaUrl, item.ctaLabel, ctx.items, classes);
    return `<a class="${e(classes)}" href="#/pulse/${e(item.id)}">Ver ${item.kind === 'workshop' ? 'taller' : 'evento'} ${icon('arrow_forward')}</a>`;
  }
  function card(item, ctx, compact = false, context = compact ? 'directory' : 'grid') {
    const current = ctx.route && ctx.route.id === item.id;
    const internship = item.kind === 'internship';
    return `<article class="card pulse-card ${compact ? 'compact' : ''}${current ? ' current-card' : ''}" data-item="${e(item.id)}" data-kind="${e(item.kind)}"><div class="card-cover ${e(item.art)}">${art(item.art)}${internship ? `<span class="company-initials" aria-label="Empresa ficticia ${e(item.company)}">${e(item.companyInitials)}</span>` : `<span class="cover-date">${e(item.date)}</span>`}</div><div class="card-body"><span class="category-label">${icon({ events: 'event', news: 'article', opportunities: 'work' }[item.category])}${e(item.label)}</span><h3><a href="#/pulse/${e(item.id)}"${current ? ' aria-current="true"' : ''}>${e(item.title)}</a></h3>${reason(item, ctx)}${topicChips(item)}<p>${e(item.summary)}</p><div class="card-meta">${icon('location_on')}<span>${e(item.location)}${internship ? ' · ' + e(item.modality) : ''}</span></div>${internship ? `<p class="pulse-deadline">Cierre de ejemplo · ${e(item.deadline)}</p>` : ''}${A.statusLabel(item, ctx.state)}${item.kind === 'article' ? `<span class="pulse-source-attribution">${e(item.source)}</span>` : item.source.startsWith('Canal CVDP') ? `<span class="pulse-channel">${e(item.source)}</span>` : ''}<div class="card-actions">${sourceCTA(item, ctx)}${saveButton(item, ctx, context)}</div></div></article>`;
  }
  function summary(ctx, count) {
    return `<div class="results-summary"><span><strong>${count}</strong> publicaciones${ctx.state.filters.pulse === 'saved' ? ' guardadas' : ''}</span><span class="saved-count">${icon('bookmark')}${ctx.state.saved.length} guardados</span></div>`;
  }
  const GROUP_SETUP = { events: 'Elegir eventos', articles: 'Elegir temas de lectura', opportunities: 'Elegir áreas' };
  function generalHint(widget) {
    return `<p class="pulse-widget-hint">${icon('tune')}Sin temas elegidos: contenido general. <a class="text-link" href="#/profile/preferences">${GROUP_SETUP[widget.id]}</a></p>`;
  }
  function emptyOpportunities() {
    return `<div class="empty-state pulse-empty-opportunities">${icon('work_history')}<h3>No hay oportunidades en tus áreas por ahora.</h3><p>Puedes consultar todas las ofertas o ajustar las áreas donde buscas oportunidades.</p><div><button type="button" class="button secondary" data-filter="pulse" data-value="opportunities">Ver todas las oportunidades</button><a class="button primary" href="#/profile/preferences">Editar mis áreas</a></div></div>`;
  }
  function emptySaved() {
    return `<div class="empty-state pulse-empty-saved">${icon('bookmark_border')}<h3>Aún no tienes publicaciones guardadas.</h3><p>Usa Guardar en una publicación para tenerla a mano aquí.</p></div>`;
  }
  function results(ctx, compact = false) {
    const items = C.getPulseItems(ctx.state, ctx.items);
    if (compact || ctx.state.filters.pulse !== 'all') return `${summary(ctx, items.length)}<div class="cards-grid ${compact ? 'compact-grid' : ''}">${items.length ? items.map(item => card(item, ctx, compact)).join('') : ctx.state.filters.pulse === 'saved' ? emptySaved() : `<div class="empty-state">${icon('search_off')}<h3>No hay publicaciones en esta categoría.</h3><button type="button" class="button secondary" data-action="clear-filters">Explorar todo</button></div>`}</div>`;
    const widgets = C.getPulseWidgets(ctx.state, ctx.items);
    return `${summary(ctx, items.length)}<div class="pulse-dashboard">${widgets.length ? widgets.map(widget => `<section class="pulse-widget" data-widget="${widget.id}" data-section="${widget.id}" aria-labelledby="widget-${widget.id}-heading"><div class="pulse-widget-heading"><div><h3 id="widget-${widget.id}-heading" tabindex="-1">${icon(widget.icon)}${widget.label}</h3><p class="pulse-widget-total">${Math.min(widget.items.length, 3)} de ${widget.items.length} ${widget.id === 'saved' ? 'guardados' : widget.id === 'events' ? 'eventos y talleres' : widget.id === 'articles' ? 'artículos' : 'oportunidades'}</p>${widget.generalContent ? generalHint(widget) : ''}</div><button class="text-link" type="button" data-filter="pulse" data-value="${widget.category}" aria-label="${widget.id === 'saved' ? 'Ver guardados' : 'Ver todos: ' + widget.label}">${widget.id === 'saved' ? 'Ver guardados' : 'Ver todos'} ${icon('arrow_forward')}</button></div><div class="cards-grid">${widget.items.length ? widget.items.slice(0, 3).map(item => card(item, ctx, false, 'dashboard-' + widget.id)).join('') : widget.emptyReason === 'no-matching-opportunities' ? emptyOpportunities() : widget.id === 'saved' ? emptySaved() : `<div class="empty-state"><h3>Aún no hay publicaciones en esta sección.</h3></div>`}</div></section>`).join('') : `<div class="empty-state pulse-empty-dashboard">${icon('dashboard_customize')}<h3>Tu dashboard tiene todas las secciones ocultas.</h3><p>Elige las secciones que quieres ver o restaura la distribución inicial.</p><div><a class="button primary" href="#/profile/preferences">Personalizar dashboard</a><button type="button" class="button secondary" data-action="restore-pulse-sections">Restaurar secciones</button></div></div>`}</div>`;
  }
  function browse(ctx, helpers = {}) {
    const title = helpers.pageTitle ? helpers.pageTitle('pulse') : `<div class="page-title"><div><span class="eyebrow">Campus Pulse</span><h1>La vida del campus empieza aquí.</h1><p>Descubre encuentros, ideas y oportunidades para ser parte.</p></div></div>`;
    return `${title}${modes(ctx)}${hero()}<div class="quick-links"><a href="#/talent"><span class="quick-icon talent">${icon('diversity_3')}</span><span><strong>Encuentra tu próximo equipo</strong><small>Explora habilidades y proyectos</small></span>${icon('arrow_forward')}</a><a href="#/mentor"><span class="quick-icon mentor">${icon('school')}</span><span><strong>Una mirada que te acompañe</strong><small>Explora tu ruta y tu red de apoyo</small></span>${icon('arrow_forward')}</a></div><section class="browse-section pulse-browse" aria-label="Campus Pulse"><div class="section-heading"><h2>Explora lo que está pasando</h2><span class="section-caption">Algo nuevo puede empezar aquí.</span></div>${filters(ctx)}<div id="results">${results(ctx)}</div></section>`;
  }
  function detail(item, ctx) {
    const internship = item.kind === 'internship';
    const event = item.category === 'events';
    const facts = internship ? `<div>${icon('work')}<span>${e(item.role)} · ${e(item.company)}</span></div><div>${icon('location_on')}<span>${e(item.location)} · ${e(item.modality)}</span></div><div>${icon('calendar_month')}<span>Cierre de ejemplo · ${e(item.deadline)}</span></div>` : `<div>${icon('calendar_month')}<span>${e(item.when)}</span></div><div>${icon('location_on')}<span>${e(item.location)}</span></div>${event ? `<div>${icon('groups')}<span>${e(item.audience)}</span></div>` : ''}`;
    return `<a class="back-link" href="#/pulse">${icon('arrow_back')}Volver a Pulse</a><article class="detail-panel pulse-detail" data-kind="${e(item.kind)}"><div class="detail-cover ${e(item.art)}">${art(item.art)}<span class="detail-cover-label">${icon('event_note')}Publicación de ejemplo</span></div><div class="detail-body"><span class="category-label">${icon({ events: 'event', news: 'article', opportunities: 'work' }[item.category])}${e(item.label)}</span><h1>${e(item.title)}</h1>${reason(item, ctx)}${topicChips(item)}<p class="detail-intro">${e(item.summary)}</p><div class="event-facts">${facts}</div>${A.detailActions(item, ctx)}${!event ? `<div class="pulse-source-action">${sourceCTA(item, ctx, C.pulseActions(item).apply ? 'button secondary' : 'button primary')}<p>${internship ? 'Consulta la descripción completa en la fuente de ejemplo.' : 'Lee el texto completo en la fuente de ejemplo.'}</p>${internship ? `<p class="pulse-eligibility-note">${icon('info')}Coincidir con tus áreas no confirma tu elegibilidad ni la aceptación de una postulación. Revisa los requisitos en la oferta completa.</p>` : ''}</div>` : ''}<div class="detail-save">${saveButton(item, ctx, 'detail', true)}<span>Tenla a mano durante esta demo.</span></div>${event ? `<div class="prose"><h2>Acerca de esta propuesta</h2><p>${e(item.detail)}</p><ul>${item.bullets.map(b => `<li>${e(b)}</li>`).join('')}</ul></div>` : ''}<div class="source-box">${icon('campaign')}<div><strong>${e(item.organizer)}</strong><span>${e(item.source)}</span></div></div><p class="concept-note">${icon('info')}${e(item.note)}</p></div></article>`;
  }
  const api = { browse, results, card, detail, filters, modes };
  if (node) module.exports = api; else root.TecPulseView = api;
})(typeof window !== 'undefined' ? window : globalThis);
