(function (root) {
  'use strict';
  var U = root.SCUI, S = root.SCState;
  var tabs = [{ id: 'reservations', label: 'Reservas' }, { id: 'attendance', label: 'Asistencias' }, { id: 'favorites', label: 'Favoritos' }, { id: 'history', label: 'Historial' }];
  function reservationCard(record) {
    var confirmed = record.status === 'confirmed';
    return '<a class="activity-card" href="#/reservation/' + record.id + '"><div class="activity-top"><span class="space-symbol tone-library">' + U.icon('local_library') + '</span><span class="badge ' + (confirmed ? 'success' : 'neutral') + '">' + (confirmed ? 'Confirmada' : 'Cancelada') + '</span></div><h2>' + U.escape(record.name) + '</h2><p>' + U.escape(U.date(record.date)) + ' · ' + U.hour(record.hour) + '–' + U.hour(record.endHour) + '</p><p>' + record.capacity + ' personas · Biblioteca</p><span class="activity-footer"><span>Ver reserva</span>' + U.icon('chevron_right') + '</span></a>';
  }
  function attendanceCard(record) {
    var active = record.status === 'active', reason = record.endReason === 'timeout' ? 'Tiempo completado' : 'Finalizado por ti';
    var status = active ? '<p class="live-line"><span class="live-dot" aria-hidden="true"></span><span><span data-countdown="' + U.escape(record.id) + '">' + U.duration(S.getSessionRemainingMs(record)) + '</span> restantes · termina ' + U.clock(record.plannedEndAt) + '</span></p>' : '<p>' + reason + ' · ' + U.clock(record.startedAt) + '–' + U.clock(record.endedAt) + ' · ' + U.span(record.endedAt - record.startedAt) + '</p>';
    return '<a class="activity-card' + (active ? ' live' : '') + '" href="#/attendance/' + U.escape(record.id) + '"><div class="activity-top"><span class="space-symbol tone-gyms">' + U.icon('fitness_center') + '</span><span class="badge ' + (active ? 'success' : 'neutral') + '">' + (active ? 'En curso' : 'Finalizada') + '</span></div><h2>' + U.escape(record.name) + '</h2>' + status + '<p>' + U.escape(U.capital(record.type)) + ' · ' + U.hours(record.duration) + ' elegida' + (record.duration === 1 ? '' : 's') + ' · ' + U.escape(U.date(record.date)) + '</p><span class="activity-footer"><span>' + (active ? 'Ver sesión en curso' : 'Ver asistencia') + '</span>' + U.icon('chevron_right') + '</span></a>';
  }
  function attendanceOrder(a, b) { return (b.status === 'active') - (a.status === 'active') || b.startedAt - a.startedAt; }
  root.SCViews.activity = function (state, ui, route) {
    var body;
    if (route.tab === 'reservations') body = state.reservations.length ? '<div class="stack">' + state.reservations.slice().reverse().map(reservationCard).join('') + '</div>' : U.empty('Sin reservas', 'Busca una sala y elige un bloque para tu próxima sesión en equipo.', 'event_available', '#/library', 'Explorar salas');
    if (route.tab === 'attendance') body = state.attendance.length ? '<div class="stack">' + state.attendance.slice().sort(attendanceOrder).map(attendanceCard).join('') + '</div>' : U.empty('Sin asistencias', 'Cuando llegues a un gimnasio, escanea el QR de la entrada para registrar tu entrenamiento. Aquí verás si sigue en curso o ya terminó.', 'fitness_center', '#/gym/gym-profesional', 'Ver gimnasios');
    if (route.tab === 'favorites') body = state.favorites.length ? '<div class="stack">' + state.favorites.map(function (id) { return U.spaceCard(S.getSpace(id), state); }).join('') + '</div>' : U.empty('Sin favoritos', 'Guarda los espacios que te interesan desde su ficha.', 'bookmark_border', '#/explore', 'Explorar espacios');
    if (route.tab === 'history') body = state.history.length ? '<div class="stack">' + state.history.slice().reverse().map(function (item) { return '<article class="history-card"><h2>' + U.escape(item.question) + '</h2><p>' + U.escape(item.title) + '</p><span class="meta">' + U.icon('history') + U.escape(U.date(item.date)) + ' · Consulta de ejemplo</span></article>'; }).join('') + '</div><button class="button ghost" style="margin-top:24px" data-action="clear-history">Borrar historial</button>' : U.empty('Sin consultas', 'Las consultas que envíes al asistente aparecerán aquí.', 'forum', '#/assistant', 'Ir al asistente');
    return U.heading('Mi actividad', 'Tus planes de campus, en un solo lugar.') + '<nav class="activity-tabs" aria-label="Tipos de actividad">' + tabs.map(function (tab) { return '<a href="#/activity/' + tab.id + '"' + (route.tab === tab.id ? ' aria-current="page"' : '') + '>' + tab.label + '</a>'; }).join('') + '</nav>' + body;
  };
  root.SCViews.profile = function (state) {
    var account = state.account;
    return U.heading('Mi cuenta', 'Tu perfil para explorar la propuesta.', '#/explore') + '<div class="profile-card"><span class="avatar" aria-hidden="true">ST</span><span class="badge">Cuenta de ejemplo</span><h2 style="margin-top:12px">Sofía Torres</h2><p>' + U.escape(account.matricula) + '</p></div><div class="profile-details"><dl class="summary-list"><div><dt>Nivel</dt><dd>' + U.escape(account.level) + '</dd></div><div><dt>Semestre</dt><dd>' + account.semester + '</dd></div><div><dt>Tipo de cuenta</dt><dd>Estudiante ficticia</dd></div></dl></div><a class="button secondary" href="#/activity/reservations">' + U.icon('calendar_month') + 'Ver mi actividad</a><div class="session-note">' + U.icon('hourglass_top') + '<div><strong>Una sesión para explorar</strong><p>Los cambios duran mientras esta página permanezca abierta. Al recargar, vuelves al inicio de la demostración.</p></div></div><section class="profile-reset"><h2>Comenzar de nuevo</h2><p>Reinicia tus reservas, asistencias, favoritos, consultas y selecciones de esta sesión.</p><button class="button ghost" data-action="reset">' + U.icon('restart_alt') + 'Reiniciar demo</button></section>';
  };
})(globalThis);
