(function (root) {
  'use strict';
  var U = root.SCUI, D = root.SCData, S = root.SCState;
  function roomDrawing(capacity) {
    var seats = [];
    for (var i = 0; i < capacity / 2; i++) { var x = 31 + i * (58 / Math.max(capacity / 2 - 1, 1)); seats.push('<rect x="' + x + '" y="8" width="13" height="9" rx="3"/><rect x="' + x + '" y="53" width="13" height="9" rx="3"/>'); }
    return '<svg viewBox="0 0 130 70" aria-hidden="true"><g fill="#e4ddef" stroke="#b7a9d0" stroke-width="1.3">' + seats.join('') + '</g><rect x="20" y="23" width="91" height="24" rx="6" fill="#f1e9d8" stroke="#cfc2a9" stroke-width="1.5"/><path d="M124 24V47" stroke="#b0a4c6" stroke-width="3"/></svg>';
  }
  function summary(room, draft) { return '<div class="booking-summary">' + U.icon('meeting_room') + '<div><strong>' + U.escape(room.name) + '</strong><span class="meta">' + U.escape(room.location.label) + '</span></div></div>'; }
  function details(record) {
    return '<dl class="summary-list"><div><dt>Fecha</dt><dd>' + U.escape(U.date(record.date)) + '</dd></div><div><dt>Horario</dt><dd>' + U.hour(record.hour) + '–' + U.hour(record.endHour || record.hour + 1) + '</dd></div><div><dt>Grupo</dt><dd>' + record.capacity + ' personas</dd></div><div><dt>Ubicación</dt><dd>Biblioteca · nivel 1 conceptual</dd></div></dl>';
  }
  root.SCViews.library = function (state) {
    var rooms = D.spaces.filter(function (space) { return space.category === 'library'; });
    return U.heading('Tu lugar para estudiar', 'Cuatro salas, un plan en equipo.', '#/explore') + '<div class="library-intro"><span class="space-symbol tone-library">' + U.icon('local_library') + '</span><div><h2>Biblioteca</h2><p>Salas de uso general · bloques de 1 hora</p></div></div><h2>Elige una sala</h2><div class="interior-plan"><div class="plan-label"><span>Plano interior conceptual</span>' + U.icon('floor') + '</div><div class="room-grid">' + rooms.map(function (room) { return '<a class="room' + (state.bookingDraft.roomId === room.id ? ' selected' : '') + '" href="#/library/' + room.id + '/book" aria-label="Elegir sala para ' + room.capacity + ' personas">' + roomDrawing(room.capacity) + '<strong>' + room.capacity + ' personas</strong><span>Sala ' + room.capacity + '</span></a>'; }).join('') + '</div><div class="plan-corridor">' + U.icon('door_front') + ' Acceso y pasillo conceptual</div></div><div class="section-heading"><h2>También puedes elegir aquí</h2></div><div class="room-list">' + rooms.map(function (room) { return '<a href="#/library/' + room.id + '/book"><span class="room-capacity">' + room.capacity + '</span><span><strong>' + U.escape(room.name) + '</strong><span class="meta">Pizarrón · conexiones eléctricas</span></span>' + U.icon('chevron_right') + '</a>'; }).join('') + '</div>' + U.message('Selecciona sala, fecha y horario. Tu reserva se guarda al confirmarla.') + U.source(rooms[0]);
  };
  root.SCViews.libraryBook = function (state, ui, route) {
    var room = S.getSpace(route.id), draft = state.bookingDraft;
    var slots = S.getLibrarySlots(state, draft), selected = slots.find(function (slot) { return slot.hour === draft.hour; });
    return U.heading('Reserva una sala', 'Organiza tu próxima sesión de estudio.', '#/library') + summary(room, draft) + '<form id="booking-form">' + U.dateField(draft.date, 'booking-date') + '<label class="field"><span>Personas en tu grupo</span><select name="capacity" id="booking-capacity">' + Array.from({ length: room.capacity }, function (_, index) { var n = index + 1; return '<option value="' + n + '"' + (draft.capacity === n ? ' selected' : '') + '>' + n + (n === 1 ? ' persona' : ' personas') + '</option>'; }).join('') + '</select><small>La sala admite hasta ' + room.capacity + ' personas.</small></label><h2>Elige tu horario</h2><div class="slot-legend"><span><i></i>Disponible</span><span><i class="occupied-dot"></i>Ocupado</span><span><i class="own-dot"></i>Tu reserva</span></div><div class="slot-grid">' + slots.map(function (slot) {
      if (slot.reason === 'own-reservation') return '<a class="time-slot own" href="#/reservation/' + U.escape(slot.reservationId) + '" aria-label="' + U.hour(slot.hour) + ' · Tu reserva. Ver reserva">' + U.hour(slot.hour) + '<span>Tu reserva</span></a>';
      return '<button type="button" class="time-slot' + (!slot.available ? ' occupied' : '') + (draft.hour === slot.hour && slot.available ? ' selected' : '') + '" data-action="library-slot" data-hour="' + slot.hour + '" aria-pressed="' + (draft.hour === slot.hour && slot.available) + '" aria-label="' + U.hour(slot.hour) + ' · ' + (slot.available ? 'Disponible' : slot.reason === 'user-conflict' ? 'Tienes otra reserva. Ver alternativas' : 'Ocupado. Ver alternativas') + '">' + U.hour(slot.hour) + '<span>' + (slot.available ? 'Disponible' : slot.reason === 'user-conflict' ? 'Otra reserva tuya' : 'Ocupado') + '</span></button>';
    }).join('') + '</div>' + U.message(ui.libraryError, 'error') + (ui.libraryAlternatives ? U.alternatives(ui.libraryAlternatives, draft.capacity) : '') + (selected && selected.available ? '<p class="record-note">Tu selección: ' + U.escape(U.date(draft.date)) + ' · ' + U.hour(draft.hour) + '–' + U.hour(draft.hour + 1) + '</p>' : '<p class="record-note">Selecciona un bloque disponible para continuar.</p>') + '<button class="button" type="submit"' + (!selected || !selected.available ? ' disabled' : '') + '>Revisar reserva' + U.icon('arrow_forward') + '</button></form>' + U.source(room);
  };
  root.SCViews.libraryReview = function (state, ui, route) {
    var room = S.getSpace(route.id), draft = state.bookingDraft;
    return U.heading('Revisa tu reserva', 'Confirma los detalles antes de guardar.', '#/library/' + room.id + '/book') + '<div class="review-card"><span class="badge">' + U.icon('local_library') + 'Biblioteca</span><h2>' + U.escape(room.name) + '</h2>' + details(draft) + '</div><section class="soft-card"><h2>Reglas de la sala</h2><div style="margin-top:12px">' + U.list(['Respeta la capacidad de la sala y el bloque de una hora.', 'Deja el espacio ordenado al terminar.', 'Cancela desde Mi actividad si tus planes cambian.']) + '</div></section>' + U.message(ui.libraryError, 'error') + (ui.libraryAlternatives ? U.alternatives(ui.libraryAlternatives, draft.capacity) : '') + '<p class="record-note">La reserva se guardará para tu cuenta de ejemplo al confirmar.</p><button class="button" data-action="confirm-reservation">Confirmar reserva</button>' + U.source(room);
  };
  root.SCViews.reservation = function (state, ui, route) {
    var record = state.reservations.find(function (item) { return item.id === route.id; });
    if (!record) return U.heading('Reserva', '', '#/activity/reservations') + U.empty('No encontramos esta reserva', 'Puedes revisar tus reservas guardadas en Mi actividad.', 'event_busy', '#/activity/reservations', 'Ver mi actividad');
    var confirmed = record.status === 'confirmed';
    return '<a class="back-link" href="#/activity/reservations">' + U.icon('arrow_back') + 'Mi actividad</a><div class="success-hero' + (!confirmed ? ' cancelled' : '') + '"><span class="success-ring">' + U.icon(confirmed ? 'check_circle' : 'event_busy') + '</span><h1>Reserva ' + (confirmed ? 'confirmada' : 'cancelada') + '</h1><p>' + (confirmed ? 'Tu equipo ya tiene un lugar para estudiar.' : 'El bloque quedó disponible de nuevo.') + '</p></div><div class="review-card"><span class="badge ' + (confirmed ? 'success' : 'neutral') + '">' + (confirmed ? 'Confirmada' : 'Cancelada') + '</span><h2>' + U.escape(record.name) + '</h2>' + details(record) + '</div><p class="record-note">Reserva de ejemplo · ' + U.escape(record.id.toUpperCase()) + '</p><div class="stack"><a class="button secondary" href="#/activity/reservations">Ver mis reservas</a>' + (confirmed ? '<button class="button ghost" data-action="cancel-reservation" data-id="' + record.id + '">Cancelar reserva</button>' : '<a class="button" href="#/library">Elegir otro horario</a>') + '</div>';
  };
})(globalThis);
