// Behavioral acceptance against the local, authored mockup. No network data or real account.
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const root = path.resolve(__dirname, '..');
const entry = path.join(root, 'index.html');
assert.ok(fs.existsSync(entry), 'Smart Campus entry screen is not implemented');
const { chromium } = require('playwright');
const D = require('../data.js');
const S = require('../state.js');
const output = path.join(root, 'review');
const base = process.env.SC_URL || 'file://' + entry;
const executable = process.env.SC_CHROMIUM || (fs.existsSync('/Applications/Google Chrome.app/Contents/MacOS/Google Chrome') ? '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome' : chromium.executablePath());
let checks = 0;
const verify = (value, message) => { assert.ok(value, message); checks++; };
const same = (actual, expected, message) => { assert.deepEqual(actual, expected, message); checks++; };

(async () => {
  fs.mkdirSync(output, { recursive: true });
  const browser = await chromium.launch({ headless: true, executablePath: executable });
  const failures = [];
  const captures = [];
  try {
    const spies = () => {
      window.__camera = 0; window.__intervals = new Set();
      const set = window.setInterval.bind(window), clear = window.clearInterval.bind(window);
      window.setInterval = (fn, ms, ...rest) => { const id = set(fn, ms, ...rest); window.__intervals.add(id); return id; };
      window.clearInterval = id => { window.__intervals.delete(id); clear(id); };
      if (navigator.mediaDevices) navigator.mediaDevices.getUserMedia = () => { window.__camera++; return Promise.reject(new Error('camera blocked in test')); };
    };
    const page = await browser.newPage({ viewport: { width: 390, height: 844 } });
    await page.addInitScript(spies);
    page.on('pageerror', error => failures.push(error.message));
    page.on('requestfailed', request => failures.push(request.url() + ': ' + request.failure()?.errorText));
    const settle = async () => { await page.evaluate(() => new Promise(resolve => requestAnimationFrame(() => requestAnimationFrame(resolve)))); await page.waitForFunction(() => document.querySelector('main h1')); await page.evaluate(() => document.fonts.ready); };
    const navigate = async hash => { await page.evaluate(value => { location.hash = value; }, hash); await settle(); };
    const text = () => page.locator('main').innerText();
    const seconds = value => value.split(':').map(Number).reduce((total, part) => total * 60 + part, 0);
    const crowd = block => block.occupancyPercent <= 30 ? 'poca gente' : block.occupancyPercent <= 60 ? 'afluencia media' : 'muy concurrido';
    const focused = selector => page.locator(selector).first().evaluate(node => node === document.activeElement);
    const screenshot = async name => { await page.locator('.toast.show').waitFor({ state: 'hidden' }); await page.waitForFunction(() => getComputedStyle(document.getElementById('toast')).opacity === '0'); await page.screenshot({ path: path.join(output, '390-' + name + '.png') }); captures.push('390-' + name + '.png'); };

    await page.goto(base); await settle();
    verify((await page.locator('body').innerText()).includes('Concepto · datos ficticios'), 'Concept marker visible');
    verify((await text()).includes('Explora'), 'Explore is the opening screen');
    await screenshot('explore-map');
    for (const category of D.categories) {
      await page.locator('[data-action="map-category"][data-category="' + category.id + '"]').click(); await settle();
      const mapIds = await page.locator('a.space-card').evaluateAll(nodes => nodes.map(node => node.getAttribute('href')).sort());
      const expectedIds = D.spaces.filter(space => space.category === category.id).map(space => '#/space/' + space.id).sort();
      same(mapIds, expectedIds, 'Map category exposes shared spaces ' + category.id);
      await page.getByRole('button', { name: 'Lista', exact: true }).click(); await settle();
      same(await page.locator('a.space-card').evaluateAll(nodes => nodes.map(node => node.getAttribute('href')).sort()), mapIds, 'Map/list equivalence ' + category.id);
      await page.getByRole('button', { name: 'Mapa', exact: true }).click(); await settle();
    }
    await page.locator('[data-action="category"][data-category="all"]').click(); await settle();
    await page.getByRole('button', { name: 'Lista', exact: true }).click(); await settle();
    await page.getByRole('button', { name: 'Filtrar por capacidad', exact: true }).click(); await settle();
    await page.getByRole('combobox', { name: 'Capacidad mínima', exact: true }).selectOption('30');
    same(await page.locator('a.space-card').count(), D.spaces.filter(space => space.capacity >= 30).length, 'Minimum capacity filters catalog');
    await page.getByRole('combobox', { name: 'Capacidad mínima', exact: true }).selectOption('0');
    await page.getByRole('button', { name: 'Filtrar por capacidad', exact: true }).click(); await settle();
    await page.getByLabel('Buscar espacios', { exact: true }).fill('solidworks');
    verify((await text()).includes(S.getSpace('computer-design').name), 'Software search finds the computer room');
    same(await page.locator('a.space-card[href="#/space/pool-main"]').count(), 0, 'Search removes unrelated result cards');
    await page.getByLabel('Buscar espacios', { exact: true }).fill('robotica');
    verify((await text()).includes(S.getSpace('lab-robotics').name), 'Accent insensitive search works');
    await navigate('#/assistant'); await navigate('#/explore');
    same(await page.getByLabel('Buscar espacios', { exact: true }).inputValue(), 'robotica', 'Search survives navigation');
    await page.getByLabel('Buscar espacios', { exact: true }).fill('');

    await navigate('#/space/lab-3d');
    await page.locator('[data-action="favorite"]').click(); await settle();
    await screenshot('lab-detail');
    await page.getByRole('link', { name: 'Ver proceso de acceso', exact: true }).click(); await settle();
    verify((await text()).includes(S.getSpace('lab-3d').responsibleArea), 'Access procedure identifies the responsible area');
    verify(/(no concede|no autoriza|no otorga|autorización)/i.test(await text()), 'Lab retains institutional authorization');
    await screenshot('lab-access');

    await navigate('#/library'); await screenshot('library-plan');
    await navigate('#/library/library-room-6/book');
    await page.getByRole('combobox', { name: 'Fecha', exact: true }).selectOption('2026-10-08');
    await page.locator('[data-action="library-slot"][data-hour="11"]').click(); await settle();
    await navigate('#/assistant'); await navigate('#/library/library-room-6/book');
    same(await page.getByRole('combobox', { name: 'Fecha', exact: true }).inputValue(), '2026-10-08', 'Booking draft date survives navigation');
    await page.getByRole('combobox', { name: 'Fecha', exact: true }).selectOption(D.demoDate);
    await page.locator('[data-action="library-slot"][data-hour="10"]').click(); await settle();
    verify((await text()).includes('Alternativas'), 'Occupied slot offers alternatives');
    same(await page.locator('[data-action="library-alternative"]').evaluateAll(nodes => nodes.map(node => ({ roomId: node.dataset.room, hour: Number(node.dataset.hour) }))), S.findRoomAlternatives(S.createState(), { roomId: 'library-room-6', date: D.demoDate, hour: 10, capacity: 6 }).map(option => ({ roomId: option.roomId, hour: option.hour })), 'Displayed alternatives use the shared domain ranking');
    await page.locator('[data-action="library-slot"][data-hour="11"]').click(); await settle();
    await screenshot('library-book');
    await page.getByRole('button', { name: 'Revisar reserva', exact: true }).click(); await settle();
    verify((await text()).includes('11:00'), 'Reservation review shows selected hour');
    await screenshot('library-review');
    await page.getByRole('button', { name: 'Confirmar reserva', exact: true }).click(); await settle();
    verify((await text()).includes('confirmada'), 'Explicit confirmation produces a reservation');
    await screenshot('reservation-confirmed');
    await navigate('#/activity/reservations');
    verify((await text()).includes(S.getSpace('library-room-6').name), 'Reservation appears in activity');
    await page.locator('a[href^="#/reservation/"]').first().click(); await settle();
    await page.getByRole('button', { name: 'Cancelar reserva', exact: true }).click(); await settle();
    await page.getByRole('button', { name: 'Confirmar cancelación', exact: true }).click(); await settle();
    verify((await text()).includes('cancelada'), 'Reservation cancellation updates its state');
    await navigate('#/library/library-room-6/book');
    verify((await page.locator('[data-action="library-slot"][data-hour="11"]').innerText()).includes('Disponible'), 'Cancellation frees the slot');
    await page.locator('[data-action="library-slot"][data-hour="11"]').click(); await settle();
    await page.getByRole('button', { name: 'Revisar reserva', exact: true }).click(); await settle();
    await page.getByRole('button', { name: 'Confirmar reserva', exact: true }).click(); await settle();

    await navigate('#/gym/gym-profesional');
    const gymSpace = S.getSpace('gym-profesional'), recommended = S.recommendGymBlocks('gym-profesional', D.demoDate)[0];
    const recommendation = await page.locator('[data-testid="gym-recommendation"]').innerText();
    verify(recommendation.includes(recommended.hour + ':00'), 'Displayed quieter time uses domain ranking');
    verify(recommendation.toLowerCase().includes(crowd(recommended)), 'Recommendation label uses the real crowd level');
    for (const fact of [gymSpace.hours, gymSpace.resources[0], gymSpace.requirements[0]]) verify((await text()).includes(fact), 'Gym page shows general information: ' + fact);
    same(await page.locator('[data-action="gym-slot"],[data-action="gym-recommendation"],.gym-hour-grid button').count(), 0, 'Availability is informational, without slot actions');
    same(await page.locator('.gym-hour-grid li').count(), S.getGymBlocks('gym-profesional', D.demoDate).length, 'Every estimated block is listed');
    await page.getByRole('combobox', { name: 'Fecha', exact: true }).selectOption('2026-10-08'); await settle();
    verify((await page.locator('[data-testid="gym-recommendation"]').innerText()).includes(S.recommendGymBlocks('gym-profesional', '2026-10-08')[0].hour + ':00'), 'Availability date select refreshes the estimate');
    await page.getByRole('combobox', { name: 'Fecha', exact: true }).selectOption(D.demoDate); await settle();
    await screenshot('gym');
    await navigate('#/gym/gym-profesional/attendance');
    verify((await page.locator('.notice.error').innerText()).includes('Primero verifica tu llegada'), 'Form without a verified arrival shows a guard');
    same(await page.locator('#attendance-form').count(), 0, 'Guard hides the attendance form');
    await page.getByRole('link', { name: 'Escanear QR de entrada', exact: true }).click(); await settle();
    same(await page.evaluate(() => location.hash), '#/gym/gym-profesional/scan', 'Guard links back to the scanner');
    await navigate('#/gym/gym-profesional');
    await page.getByRole('link', { name: 'Registrar asistencia', exact: true }).click(); await settle();
    same(await page.evaluate(() => location.hash), '#/gym/gym-profesional/scan', 'Registrar asistencia opens the entrance scanner');
    verify((await text()).includes('Escaneo simulado · concepto: en la versión real se abriría la cámara'), 'Scanner states it is simulated');
    await screenshot('gym-scan');
    await page.getByRole('button', { name: 'Probar con el QR del otro gimnasio', exact: true }).click(); await settle();
    verify((await text()).includes('pertenece a otro gimnasio'), 'Wrong-gym QR is rejected');
    verify(await focused('.notice.error'), 'Wrong-gym error receives focus');
    same(await page.evaluate(() => location.hash), '#/gym/gym-profesional/scan', 'Rejected scan stays on the scanner');
    await page.getByRole('button', { name: 'Simular escaneo del QR de entrada', exact: true }).click(); await settle();
    same(await page.evaluate(() => location.hash), '#/gym/gym-profesional/attendance', 'Correct QR opens the attendance form');
    verify((await text()).includes('Llegada verificada'), 'Form confirms the verified arrival');
    verify((await text()).includes(D.account.matricula), 'Attendance account data is automatically populated');
    same(await page.locator('input[name="duration"]').evaluateAll(nodes => nodes.map(node => Number(node.value))), D.gymRules.durations, 'Duration options come from gym rules');
    await page.getByRole('combobox', { name: 'Tipo de entrenamiento', exact: true }).selectOption('cardio');
    await page.getByLabel('1.5 horas', { exact: true }).check();
    await navigate('#/explore'); await navigate('#/gym/gym-profesional/attendance');
    same(await page.getByRole('combobox', { name: 'Tipo de entrenamiento', exact: true }).inputValue(), 'cardio', 'Attendance draft survives navigation');
    verify(await page.getByLabel('1.5 horas', { exact: true }).isChecked(), 'Duration choice survives navigation');
    await screenshot('gym-form');
    await page.getByRole('button', { name: 'Registrar', exact: true }).click(); await settle();
    same(await page.evaluate(() => location.hash), '#/attendance/attendance-1', 'Registrar starts a session');
    verify((await text()).includes('Entrenamiento en curso'), 'Session screen shows the running state');
    const timer = page.getByRole('timer');
    same(await timer.getAttribute('aria-live'), 'off', 'Countdown does not spam screen readers');
    const firstReading = await timer.innerText();
    verify(seconds(firstReading) > 5390 && seconds(firstReading) <= 5400, 'Countdown starts at the chosen duration');
    await page.getByRole('button', { name: 'Finalizar entrenamiento', exact: true }).focus();
    await page.evaluate(() => { document.querySelector('.countdown-card').dataset.probe = 'kept'; });
    await page.waitForFunction(value => document.querySelector('[role="timer"]').textContent !== value, firstReading, { timeout: 4000 });
    verify(seconds(await timer.innerText()) < seconds(firstReading), 'Countdown decreases');
    verify(await focused('[data-action="finish-session"]'), 'Countdown ticks keep keyboard focus');
    same(await page.locator('.countdown-card').getAttribute('data-probe'), 'kept', 'Ticks update text without re-rendering the screen');
    same(await page.evaluate(() => window.__intervals.size), 1, 'A single interval drives the timer');
    await screenshot('gym-session');
    await navigate('#/activity/attendance');
    verify((await text()).includes('En curso') && (await text()).includes('restantes'), 'Activity shows the running session');
    const activityReading = await page.locator('.activity-card [data-countdown]').innerText();
    await page.waitForFunction(value => document.querySelector('.activity-card [data-countdown]').textContent !== value, activityReading, { timeout: 4000 });
    verify(true, 'Activity countdown updates live');
    await navigate('#/gym/gym-profesional');
    verify((await text()).includes('Tu sesión está en curso aquí'), 'Gym page shows your presence');
    same(await page.getByRole('link', { name: 'Registrar asistencia', exact: true }).count(), 0, 'Active session replaces the register button');
    verify((await page.locator('.session-banner').innerText()).includes('Entrenamiento en curso'), 'Gym page links to the running session');
    await navigate('#/gym/gym-prepatec/scan');
    await page.getByRole('button', { name: 'Simular escaneo del QR de entrada', exact: true }).click(); await settle();
    verify((await text()).includes('Ya tienes un entrenamiento en curso'), 'Second scan is rejected while a session runs');
    verify(await focused('.notice.error'), 'Active-session error receives focus');
    await page.getByRole('link', { name: 'Ver entrenamiento en curso', exact: true }).click(); await settle();
    same(await page.evaluate(() => location.hash), '#/attendance/attendance-1', 'Active-session error links to the session');
    await page.getByRole('button', { name: 'Finalizar entrenamiento', exact: true }).click(); await settle();
    await page.getByRole('button', { name: 'Confirmar finalización', exact: true }).click(); await settle();
    verify((await text()).includes('Entrenamiento finalizado') && (await text()).includes('Finalizado por ti'), 'Manual finish records its reason');
    verify(await focused('main h1'), 'Focus returns to the heading after finishing');
    same(await page.evaluate(() => window.__intervals.size), 0, 'Timer stops when no session is active');
    await navigate('#/gym/gym-prepatec/scan');
    await page.getByRole('button', { name: 'Simular escaneo del QR de entrada', exact: true }).click(); await settle();
    await page.getByRole('combobox', { name: 'Tipo de entrenamiento', exact: true }).selectOption('pierna');
    await page.getByRole('button', { name: 'Registrar', exact: true }).click(); await settle();
    same(await page.evaluate(() => location.hash), '#/attendance/attendance-2', 'A new session can start after finishing');
    await page.getByRole('button', { name: 'Demo · simular fin del tiempo', exact: true }).click(); await settle();
    verify((await text()).includes('Tiempo completado'), 'Simulated timeout finishes by time');
    verify(await focused('main h1'), 'Simulated timeout moves focus to the heading');
    await screenshot('gym-finished');
    await navigate('#/activity/attendance');
    same(await page.locator('.activity-card .badge').allInnerTexts(), ['Finalizada', 'Finalizada'], 'Activity reflects finished sessions');
    verify((await text()).includes('Tiempo completado') && (await text()).includes('Finalizado por ti'), 'Activity shows each end reason');
    same(await page.evaluate(() => window.__camera), 0, 'The demo never requests the device camera');

    await navigate('#/library/library-room-6/book');
    await page.locator('[data-action="library-slot"][data-hour="12"]').click(); await settle();
    await navigate('#/assistant');
    await page.getByRole('textbox', { name: 'Tu consulta', exact: true }).fill('');
    await page.getByRole('button', { name: 'Consultar', exact: true }).click(); await settle();
    same(await page.locator(':focus').getAttribute('id'), 'assistant-query', 'Blank query validation returns focus to the query field');
    for (const [prompt, scenario] of [[1, 'library'], [2, 'lab'], [3, 'gym']]) {
      await page.locator('[data-action="assistant-prompt"]').nth(prompt).click(); await settle();
      await page.getByRole('button', { name: 'Consultar', exact: true }).click(); await settle();
      verify((await text()).includes('Respuesta de ejemplo'), 'Assistant response identifies scripted example ' + scenario);
      verify(await page.locator('.assistant-response').evaluate(node => node.contains(document.activeElement)), 'Assistant response receives focus for its next action');
      await screenshot('assistant-' + scenario);
      await page.locator('[data-action="assistant-action"]').first().click(); await settle();
      if (scenario === 'library') {
        verify((await text()).includes('12:00'), 'Assistant room action carries selected hour');
        await navigate('#/activity/reservations');
        same(await page.locator('a[href^="#/reservation/"]').count(), 2, 'Assistant suggestion does not reserve without confirmation');
      } else if (scenario === 'lab') {
        verify((await text()).includes(S.getSpace('lab-3d').name), 'Assistant lab action opens shared laboratory information');
      } else {
        verify(/^#\/gym\/gym-(profesional|prepatec)$/.test(await page.evaluate(() => location.hash)) && (await text()).includes('Registrar asistencia'), 'Assistant gym action opens the gym page');
        await navigate('#/activity/attendance');
        same(await page.locator('a[href^="#/attendance/"]').count(), 2, 'Assistant suggestion does not record attendance');
      }
      await navigate('#/assistant');
    }
    await page.locator('[data-action="assistant-prompt"]').first().click(); await settle();
    await page.getByRole('button', { name: 'Consultar', exact: true }).click(); await settle();
    const bookingAnswer = await page.locator('.assistant-response').innerText();
    verify(bookingAnswer.includes(S.getSpace('library-room-4').name) && bookingAnswer.includes('Vie 9 oct') && bookingAnswer.includes('11:00') && bookingAnswer.includes('grupo de 4'), 'Chat booking answer respects date, hour and group size');
    await screenshot('assistant-booking');
    await page.getByRole('button', { name: 'Revisar reserva', exact: true }).first().click(); await settle();
    same(await page.evaluate(() => location.hash), '#/library/library-room-4/book', 'Chat booking opens the suggested room');
    same(await page.getByRole('combobox', { name: 'Fecha', exact: true }).inputValue(), '2026-10-09', 'Chat booking carries the date');
    same(await page.locator('#booking-capacity').inputValue(), '4', 'Chat booking carries the group size');
    same(await page.locator('[data-action="library-slot"][data-hour="11"]').getAttribute('aria-pressed'), 'true', 'Chat booking carries the hour');
    await navigate('#/activity/reservations');
    same(await page.locator('a[href^="#/reservation/"]').count(), 2, 'Chat booking creates nothing before confirmation');
    await navigate('#/library/library-room-4/book');
    await page.getByRole('button', { name: 'Revisar reserva', exact: true }).click(); await settle();
    await page.getByRole('button', { name: 'Confirmar reserva', exact: true }).click(); await settle();
    verify((await text()).includes('confirmada'), 'Chat booking is created only on explicit confirmation');
    await navigate('#/assistant');
    const refreshed = await page.locator('.answer-option').allInnerTexts();
    verify(refreshed.length > 0 && refreshed.every(option => !option.includes('11:00–12:00')), 'Assistant answer refreshes and drops the booked 11:00 offer');
    await page.getByRole('textbox', { name: 'Tu consulta', exact: true }).fill('¿Cuánto cuesta mi colegiatura?');
    await page.getByRole('button', { name: 'Consultar', exact: true }).click(); await settle();
    verify((await text()).includes('ejemplos'), 'Unsupported query offers supported examples');
    same(await page.locator('[data-action="assistant-action"]').count(), 0, 'Unsupported query offers no operation');
    await navigate('#/activity/history');
    verify((await text()).includes('colegiatura'), 'Consultations appear in history');
    await page.getByRole('button', { name: 'Borrar historial', exact: true }).click(); await settle();
    await page.getByRole('button', { name: 'Confirmar borrado', exact: true }).click(); await settle();
    verify((await text()).includes('Sin consultas'), 'History clear removes consultations');
    await navigate('#/activity/reservations'); verify((await text()).includes('Confirmada'), 'History deletion preserves reservations');
    await navigate('#/activity/attendance'); verify((await text()).includes('Cardio'), 'History deletion preserves attendance');
    await navigate('#/activity/favorites'); verify((await text()).includes(S.getSpace('lab-3d').name), 'History deletion preserves favorites');
    await screenshot('activity-favorites');

    await navigate('#/gym/gym-profesional/scan');
    await page.getByRole('button', { name: 'Simular escaneo del QR de entrada', exact: true }).click(); await settle();
    await page.getByRole('button', { name: 'Registrar', exact: true }).click(); await settle();
    same(await page.evaluate(() => window.__intervals.size), 1, 'Timer runs before reset');
    await navigate('#/profile'); await screenshot('profile');
    await page.getByRole('button', { name: 'Reiniciar demo', exact: true }).click(); await settle();
    await page.getByRole('button', { name: 'Confirmar reinicio', exact: true }).click(); await settle();
    same(await page.evaluate(() => location.hash), '#/explore', 'Reset returns to the opening screen');
    same(await page.evaluate(() => window.__intervals.size), 0, 'Reset stops the session timer');
    await navigate('#/activity/reservations'); verify((await text()).includes('Sin reservas'), 'Reset restores empty reservations');
    await navigate('#/activity/attendance'); verify((await text()).includes('Sin asistencias'), 'Reset clears attendance');
    await navigate('#/activity/favorites'); verify((await text()).includes('Sin favoritos'), 'Reset clears favorites');
    await navigate('#/activity/history'); verify((await text()).includes('Sin consultas'), 'Reset clears history');
    await page.reload(); await settle();
    await navigate('#/explore');
    same(await page.getByLabel('Buscar espacios', { exact: true }).inputValue(), '', 'Reload restores clean search');

    const routes = ['#/explore', '#/library', '#/library/library-room-6/book', '#/gym/gym-profesional', '#/gym/gym-prepatec', '#/gym/gym-profesional/scan', '#/gym/gym-profesional/attendance', '#/assistant', '#/profile', '#/activity/reservations', ...D.spaces.map(space => '#/space/' + space.id)];
    for (const width of [360, 390, 430, 1440]) {
      await page.setViewportSize({ width, height: width > 500 ? 1000 : 844 });
      for (const route of routes) {
        await navigate(route);
        const dimensions = await page.evaluate(() => ({ viewport: innerWidth, document: document.documentElement.scrollWidth, body: document.body.scrollWidth, frame: document.querySelector('.phone').getBoundingClientRect().width, font: [...document.fonts].some(font => font.family === 'Poppins' && font.status === 'loaded'), main: document.querySelector('main').scrollWidth, mainClient: document.querySelector('main').clientWidth }));
        verify(dimensions.document <= width + 1 && dimensions.body <= width + 1 && dimensions.main <= dimensions.mainClient + 1, 'No horizontal overflow ' + width + ' ' + route);
        verify(dimensions.font, 'Local Poppins loaded ' + width + ' ' + route);
        if (width === 1440) verify(dimensions.frame <= 460, 'Presentation keeps phone layout ' + route);
        verify((await page.locator('body').innerText()).includes('Concepto · datos ficticios'), 'Concept marker persists ' + route);
      }
      await navigate('#/explore');
      await page.screenshot({ path: path.join(output, width + '-explore.png') }); captures.push(width + '-explore.png');
    }
    await page.goto(base); await settle();
    await page.keyboard.press('Tab');
    same(await page.locator(':focus').innerText(), 'Saltar al contenido', 'Skip link is the first keyboard stop');
    await page.keyboard.press('Enter');
    same(await page.evaluate(() => location.hash), '#/explore', 'Skip link preserves application route');
    verify(await page.locator('main').evaluate(node => node.contains(document.activeElement) || node === document.activeElement), 'Skip link focuses content');
    await navigate('#/library/library-room-6/book');
    await page.locator('[data-action="library-slot"][data-hour="11"]').click(); await settle();
    await page.getByRole('button', { name: 'Revisar reserva', exact: true }).click(); await settle();
    await page.getByRole('button', { name: 'Confirmar reserva', exact: true }).click(); await settle();
    await page.reload(); await settle();
    same(await page.evaluate(() => location.hash), '#/explore', 'Reloading a receipt restores Explore rather than a missing-record screen');
    await navigate('#/activity/reservations'); verify((await text()).includes('Sin reservas'), 'Reloading a receipt clears its in-memory reservation');
    await navigate('#/missing');
    same(await page.evaluate(() => location.hash), '#/explore', 'Unknown routes recover to Explore');
    const clocked = await browser.newPage({ viewport: { width: 390, height: 844 } });
    clocked.on('pageerror', error => failures.push(error.message));
    await clocked.clock.install({ time: new Date(2026, 9, 7, 10, 0) });
    await clocked.goto(base + '#/gym/gym-prepatec/scan'); await clocked.waitForFunction(() => document.querySelector('main h1'));
    await clocked.getByRole('button', { name: 'Simular escaneo del QR de entrada', exact: true }).click();
    await clocked.locator('#attendance-form').waitFor();
    await clocked.clock.fastForward('10:01');
    await clocked.getByRole('button', { name: 'Registrar', exact: true }).click();
    verify((await clocked.locator('.notice.error').innerText()).includes('expiró'), 'Expired arrival is rejected on submit');
    verify(await clocked.locator('.notice.error').evaluate(node => node === document.activeElement), 'Expired arrival error receives focus');
    await clocked.getByRole('link', { name: 'Escanear QR de entrada', exact: true }).click();
    await clocked.getByRole('button', { name: 'Simular escaneo del QR de entrada', exact: true }).click();
    await clocked.locator('#attendance-form').waitFor();
    await clocked.getByRole('button', { name: 'Registrar', exact: true }).click();
    await clocked.getByRole('timer').waitFor();
    verify((await clocked.locator('main').innerText()).includes('Entrenamiento en curso'), 'Clocked session starts');
    await clocked.clock.fastForward('01:00:02');
    await clocked.waitForFunction(() => document.querySelector('main').innerText.includes('Tiempo completado'), null, { timeout: 4000 });
    verify((await clocked.locator('#toast').innerText()).includes('Tiempo completado. Entrenamiento finalizado.'), 'Timer reaching zero finishes the session and announces it');
    verify((await clocked.locator('main h1').innerText()).includes('Entrenamiento finalizado'), 'Timer reaching zero shows the finished screen');
    await clocked.close();
    same(failures, [], 'No browser or local asset errors');
    fs.writeFileSync(path.join(output, 'acceptance-results.json'), JSON.stringify({ status: 'PASS', checks, widths: [360, 390, 430, 1440], routes: routes.length, directFile: base.startsWith('file:'), captures, failures }, null, 2));
    console.log('PASS: ' + checks + ' browser acceptance checks; ' + captures.length + ' screenshots; direct local opening; zero runtime/asset errors.');
  } finally { await browser.close(); }
})().catch(error => { console.error(error.stack); process.exitCode = 1; });
